// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resto.infrastructure.Data;

#nullable disable

namespace resto.infrastructure.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20241021143409_UpdateCommande")]
    partial class UpdateCommande
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("resto.domain.Entities.Commande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantiteProduit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("resto.domain.Entities.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("resto.domain.Entities.Commande", b =>
                {
                    b.HasOne("resto.domain.Entities.Produit", "Produit")
                        .WithMany("Commande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("resto.domain.Entities.Produit", b =>
                {
                    b.Navigation("Commande");
                });
#pragma warning restore 612, 618
        }
    }
}
